### ISSUE TITLE
Change details for client

### ISSUE THREAD

**Issue by ericbraz** [brunorplima/divino-dog-menu-app#123]
Change the following details:

- Colors;
- Logo;
- Store description;
- Creators description.

**Comment by brunorplima** [comment]
@ericbraz When choosing the color, try to use the colors given by tailwind. It helps us to keep consistence among pages by using always only 3 shades of that color.
If the color it provides it's too far from what you imagined (I believe it's a brownish color that we saw in their ads) then instead of using tailwind, create global CSS variables with the values of the colors to keep that consistency. All colors heavily used in the app should have its own global variable to be used on the pages.
I will work on my description today and tomorrow and I will let you know when I have it ready.
